# Generated by Django 3.2.4 on 2021-06-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('techonologies', models.TextField(max_length=300)),
                ('img_1', models.ImageField(upload_to='images\\project')),
                ('img_2', models.ImageField(upload_to='images\\project')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
