# Generated by Django 3.2.4 on 2021-06-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_url_project_purl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='techonologies',
            new_name='technologies',
        ),
    ]
