# Generated by Django 3.2.4 on 2021-06-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contactme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
